name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material~=9.5.17 cairosvg~=2.7.1 pillow~=10.3.0
      - run: mkdocs gh-deploy --force